services:
  orchestrator:
    build: .
    env_file: .env
    volumes:
      - orchestrator-db:/app
    ports:
      - "8000:8000"
    environment:
      DOCKER_HOST: tcp://docker:2375
    depends_on:
      docker:
        condition: service_healthy
    restart: on-failure
  docker:
    image: docker:27.3.1-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    ports:
      - "2375:2375"
    volumes:
      - docker-data:/var/lib/docker
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  docker-data:
  orchestrator-db:
